SUBJECTS: [1]
MODE: all
TRANSFORMER: FAST_CSP
EXPERIMENT: imagery_vs_action__feets

# SUBJECTS:
#    list of numbers between 1-100 or empty array
#    examples:
#       - [1,2,3,42] : subjects selected are 1,2,3,42 only
#       - [] : all subjects will be selected from 1 to 109
# MODE:
#    train
#    predict

# TRANSFORMERS:
#    CSP
#    SPoC
#    FAST_CSP

# EXPERIMENTS:
#    hands_vs_feet__action
#    hands_vs_feet__imagery
#    imagery_vs_action__hands
#    imagery_vs_action__feets
